

mode = 'justRun'; % justRun | validateWhatever FIXME TBD
sp   = {' '};

% test_dirs   = {...
%                'dimensioning', ...
%                'PFCNano', ... % This is heavy load for the computer
%                'energy',...
%                'inducedVelocity',...
%                'trim',...
%                'stability' ...
%               };

test_dirs   = {...
               'dimensioning', ...
               'energy',...
               'flightDynamics',...
               'inducedVelocity',...
               'trim',...
               'stability',...
               'validation' ...
               };
% ===================================================================
% Run heroes tests in justRun mode, took 1452.0358 seconds
% ===================================================================

tic
for i=1:length(test_dirs)
    exename = str2func(strcat(test_dirs{i},'tester'));
    cd(test_dirs{i}); 
    exename(mode); 
    cd ..
end
mTest = toc;

disp('===================================================================')
disp(char(strcat('Run heroes tests in',sp,mode,sp,'mode, took',sp,num2str(mTest),sp,'seconds')))
disp('===================================================================')