function [optStatHe, Svt, cHTP] = optionDataBo105
%OPTIONDATABO105 Resumes the Main aerodynamic data needed for the complete
%rigid definition for the Bo105
%   This function contains specific data about aerodynamic elements like
%   the main rotor, tail rotor, fuselage, vertical fin, horizontal fin and
%   geometric.

% vertical fin surface
Svt = .805;

% horizontal tail plane chord
cHTP = .4;


% Define the option structures to define the properly the data for 
% Bo105 that it is required for 
optMR   = struct(...
          'e',0.0,...
          'theta1',-8*pi/180,...
          'cldata',[6.113 0],...
          'cddata',[0.0074 0.00961 0.29395],...
          'kBeta', 113330 ...
);

optTR   = struct(...
          'e',0.0,...
          'theta1',0,...
          'cldata',[5.7 0],...
          'cddata',[0.008 0.00961 0.29395],...
          'kBeta', 1e100 ...
);


optF    = struct(...
          'model',@generalFus,...
          'kf',1 ...
);

optVF = struct(...
          'airfoil',@naca0012,...
          'theta',4.6501*pi/180 ...
);

optLHTP = struct(...
          'airfoil',@naca0012,...
          'theta',4.*pi/180 ...
);

optRHTP = struct(...
          'airfoil',@naca0012,...
          'theta',4.*pi/180 ...
);

optGeom = struct(...
          'xcg',0.08033,...
          'epsilony',-3*pi/180, ...
          'dtr',-0.3 ...
);


optStatHe = struct(...
      'mainRotor',optMR,...
      'tailRotor',optTR,...
      'fuselage',optF,...
      'verticalFin',optVF,...
      'leftHTP',optLHTP,...
      'rightHTP',optRHTP,...
      'geometry',optGeom ...
);

end

