function mission = missionIni(he,atm,PL0,Mf0,RF,varargin)
% missionIni builds a initial segment common to all the missions for a
% given helicopter, he, atmosphere, atm, mission builder, mission, initial 
% payload, PL0, initial fuel mass, Mf0, and fuel reserve, RF.
% This dummy segment corresponds to a Hover type segment.
%
% The output of this function is a structure with the following fields:
%
%     class: 'missionSegment'
%        id: 'Hover'
%    solver: @getSegmentHover
%       pos: [1x1 double]
%         V: [1x2 double]
%    gammaT: [1x2 double]
%        VH: [1x2 double]
%        VV: [1x2 double]
%     Omega: [1x2 double]
%         Z: [1x2 double]
%         H: [1x2 double]
%        DH: [1x1 double]
%         R: [1x2 double]
%        DR: [1x1 double]
%         T: [1x2 double]
%        DT: [1x1 double]
%        GW: [1x2 double]
%       DGW: [1x1 double]
%        Mf: [1x2 double]
%       DMf: [1x1 double]
%        PL: [1x2 double]
%       DPL: [1x1 double]
%         P: [1x2 double]
%

options   = parseOptions(varargin,@setHeroesEnergyOptions);

missionSettings = struct('PL0',PL0,'Mf0',Mf0,'RF',RF);

GW0 = he.weights.OEW+Mf0*atm.g+PL0+RF*atm.g;

Z     = 1.5*he.mainRotor.R;
Omega = he.mainRotor.Omega;

fC = getFlightCondition(he,...
                          'V',0,...
                          'gammaT',0,...
                          'Vh',[],...
                          'Vv',[],...
                          'H',0,...
                          'GW',GW0,...
                          'Z',Z);


EpS = getEpowerState(he,fC,atm,options);
  
   P = EpS.P;

missSeg{1} = struct(...
    'class','missionSegment',...
       'id','InitialHover',...
      'pos',1,...
        'V',[0 0],...
   'gammaT',[0 0],...
       'VH',[0 0],...
       'VV',[0 0],...
    'Omega',[Omega Omega],...
        'Z',[Z Z],...
        'H',[0 0],...
       'DH',0,...
        'R',[0 0],...
       'DR',0,...
        'T',[1 1],...
       'DT',0.5,...
       'GW',[GW0 GW0],...
      'DGW',0,...
       'Mf',[Mf0 Mf0],...
      'DMf',0,...
       'PL',[PL0 PL0],...
      'DPL',0,...
        'P',[P P] ...
          );
      

mission = struct('missSet',missionSettings,...
                 'mSeg',{missSeg});
end


