function [iniTrimCon,xTrimOrder] = getInitialTrimConditions(ndHe,S0)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here


%strcmp(trimType,'straightFlight')
xTrimOrder = struct(...
'Theta',1,'Phi',2,'theta0',3,'theta1C',4,'theta1S',5,...       
'theta0tr',6,'beta0',7,'beta1C',8,'beta1S',9,'lambda0',10,...          
'lambda1C',11,'lambda1S',12,'CT0',13,'CT1C',14,'CT1S',15,...                  
'beta0tr',16,'beta1Ctr',17,'beta1Str',18,'lambda0tr',19,...
'lambda1Ctr',20,'lambda1Str',21,'CT0tr',22,'CT1Ctr',23,...
'CT1Str',24,'omega',25,'Psi',26,'uTOR',27,'vTOR',28,...
'wTOR',29,'ueOR',30,'veOR',31,'weOR',32,'omxad',33,...
'omyad',34,'omzad',35,'omegaAdzT',36,'VOR',37,...
'gammaT',38,'betaT',39,'betaf0',40,'alphaf0',41,...
'cs',42 ...
);



 if isstruct(S0)
     
     
 
     iniTrimCon = rmfield(S0,'class');

 else 

     iniTrimCon = setIniTrimConDefaults(ndHe);

 end

end

function iniTrimConDefaults = setIniTrimConDefaults(ndHe)

CWrated = ndHe.inertia.CW;
theta0ini = -ndHe.mainRotor.theta1+2*pi/180;

iniTrimConDefaults = struct(...
'Theta'     ,0,...      
'Phi'       ,0,...        
'theta0'    ,theta0ini,...          
'theta1C'   ,0,...     
'theta1S'   ,0,...       
'theta0tr'  ,0,...           
'beta0'     ,0,...         
'beta1C'    ,0,...           
'beta1S'    ,0,...              
'lambda0'   ,-sqrt(CWrated/2),...            
'lambda1C'  ,0,...    
'lambda1S'  ,0,...             
'CT0'       ,CWrated,...             
'CT1C'      ,0,...               
'CT1S'      ,0,...                  
'beta0tr'   ,0,...               
'beta1Ctr'  ,0,...
'beta1Str'  ,0,...       
'lambda0tr' ,-sqrt(CWrated/20),...
'lambda1Ctr',0,...
'lambda1Str',0,...
'CT0tr'     ,0,...
'CT1Ctr'    ,0,...
'CT1Str'    ,0,...
'omega'     ,1,...
'Psi'       ,0,...
'uTOR'      ,0,...
'vTOR'      ,0,...
'wTOR'      ,0,...
'ueOR'      ,0,...
'veOR'      ,0,...
'weOR'      ,0,...
'omxad'     ,0,...
'omyad'     ,0,...
'omzad'     ,0,...
'omegaAdzT' ,0,...
'VOR'       ,0,...
'gammaT'    ,0,...
'betaT'     ,0,...
'betaf0'    ,0,...
'alphaf0'   ,0,...
'cs'        ,0 ...
);


end
