function trimVars = getTrimVarsNames


trimVars = {'Theta','Phi','theta0','theta1C','theta1S',...       
'theta0tr','beta0','beta1C','beta1S','lambda0',...          
'lambda1C','lambda1S','CT0','CT1C','CT1S',...                  
'beta0tr','beta1Ctr','beta1Str','lambda0tr',...
'lambda1Ctr','lambda1Str','CT0tr','CT1Ctr',...
'CT1Str','omega','Psi','uTOR','vTOR',...
'wTOR','ueOR','veOR','weOR','omxad',...
'omyad','omzad','omegaAdzT','VOR',...
'gammaT','betaT','betaf0','alphaf0','cs'};

end

