function plotSimpAMPract(amS,legend,varargin)

if length(varargin)==1 
   while iscell(varargin) && length(varargin)==1
      varargin = varargin{1};
   end
end

r2d    = 180/pi;



% axesData.xvar = 'theta1S';
% axesData.xlab = '\theta_{1S} [?]';
% axesData.xunit = r2d;

% axesData.yvars = {'beta0' 'beta1C' 'beta1S' 'lambda0' ...
%         'CH' 'CY' 'CT'...
%         'CME2Fx' 'CME2Fy' 'CME2Fz' 'CMax' 'CMay' 'CMaz'};
% axesData.ylabs = {'\beta_0 [?]' '\beta_{1C} [?]' '\beta_{1S} [?]' '\lambda_0 [-]' ...
%         'C_{H} [-]' 'C_{Y} [-]' 'C_{T} [-]' ...
%         'C_{Mx_A}^{a,E}/C_{Mx_A}^{F^a} [-]'...
%         'C_{My_A}^{a,E}/C_{My_A}^{F^a} [-]'...
%         'C_{Mz_A}^{a,E}/C_{Mz_A}^{F^a} [-]'...
%         'C_{Mx_A}^a [-]' 'C_{My_A}^a [-]' 'C_{Mz_A}^a [-]'};
% axesData.yunits = [r2d r2d r2d 1 1 1 1 1 1 1 1 1 1];
% 
% 
% pairs = varargin;
% 
% plotOpt = parseOptions(pairs,@setHeroesPlotOptions);
% plotOpt.mode = 'thick';
% plotCellOfStructures(amS,axesData,legend,plotOpt);
%


axds = getaxds('theta1S','$$\theta_{1S}$$ [$$^o$$]',r2d);
azds = getaxds( ...
{'beta0' 'beta1C' 'beta1S' 'lambda0' ...
'CH' 'CY' 'CT'...
'CME2Fx' 'CME2Fy' 'CME2Fz' 'CMax' 'CMay' 'CMaz'},...
{'\beta_0 [^o]' '\beta_{1C} [^o]' '\beta_{1S} [^o]' '\lambda_0 [-]' ...
'C_{H} [-]' 'C_{Y} [-]' 'C_{T} [-]' ...
'C_{Mx_A}^{a,E}/C_{Mx_A}^{F^a} [-]'...
'C_{My_A}^{a,E}/C_{My_A}^{F^a} [-]'...
'C_{Mz_A}^{a,E}/C_{Mz_A}^{F^a} [-]'...
'C_{Mx_A}^a [-]' 'C_{My_A}^a [-]' 'C_{Mz_A}^a [-]'},...
[r2d r2d r2d 1 1 1 1 1 1 1 1 1 1]);

pairs = varargin;

plotOpt = parseOptions(pairs,@setHeroesPlotOptions);
plotOpt.mode = 'thick';
plotCellOfStructures(amS,axds,azds,legend,plotOpt);