function trimtester(mode)

% trim tests
% TODO tests that do not work (oslo: March, 7th)
% * rotorFlapOmegaTest outdated (Nano)
% * test_energyVStrim outdated (Cesar)
% * trimClass outdated (Nano)
% * rotorTrimTest outdated (Nano)
% * rotorFlapThetaTest outdated (Nano)
% * aeromechanicsClass outdated (Nano)
% * aeromechanicsPract outdated (Nano)
% * aeromechanicsTest outdated (Nano)
% * rotorTrimTest2 outdated (Nano)
% * aeromechanicsClass1 outdated (Nano)
% * flappingtest outdated (Nano)
% * testTrimRigidRotorTrim runs but it needs documentation
testList  = {...
             @aeromechanicPhaseShift,...
             @hoverFlappingTest ...
             @test_plotRigidHeDatabase ...
             @test_plotRigidHePreview ...
             @trim01 ...
             @trim02 ...
             @trimPFCnano ...
             @trimTest ...
             @test_plotTrimState ...
             @test_checkTrimReferenceHA2 ...
             @testTrimRigidRotorTrim ...
            };

runTestList(testList,mode);

% for i=1:length(test),
%     io = test{i}();
%     runCheckTest(io,func2str(test{i}));
%     close all
% end