function dr = dimhe2dimdr(heliplusdr)
%
% This function extracts the DR from a dimensional statistical helicopter
% with the DR appended into the structure.

rand = struct( ...
                        'MTOW',heliplusdr.Weights.MTOW,...
                       'Range',heliplusdr.Performances.Range,...
                          'Vm',heliplusdr.Performances.VmaxSeaLevel,...
                           'b',heliplusdr.MainRotor.b,...
                         'btr',heliplusdr.TailRotor.b,...
                        'Crew',heliplusdr.DR.rand.Crew ...
);

estimations = heliplusdr.DR.estimations;
technologyFactors = heliplusdr.DR.technologyFactors;
costFactors = heliplusdr.DR.costFactors;
mission = heliplusdr.DR.mission;
options = heliplusdr.DR.options;

energyEstimations = heliplusdr.DR.energyEstimations;

dr = struct(...
  'class','desreq',...
  'id',heliplusdr.DR.id,...
  'rand',rand,...
  'technologyFactors',technologyFactors,...
  'costFactors',costFactors,...
  'mission',mission,...
  'options',options,...
  'energyEstimations',energyEstimations,...
  'estimations',estimations ...
);
    

