function g = geometry2ndGeometry(geometry,R)
%GEOMETRY2NDGEOMETRY  Transforms a dimensional helicopter geometric data
%                     struct into a nondimensional one
%
%   P = GEOMETRY2NDGEOMETRY(G,R) computes a nondimensional geometry P from
%   a dimensional one G, given the main rotor radius R.
%

g = struct(...
        'Xcg',geometry.xcg/R,...
        'Ycg',geometry.ycg/R,...
        'Zcg',geometry.zcg/R,...
        'epsilonx',geometry.epsilonx,...
        'epsilony',geometry.epsilony,...
        'ndls',geometry.ls/R,...
        'ndds',geometry.ds/R,...
        'ndh',geometry.h/R,...
        'thetatr',geometry.thetatr,...
        'ndltr',geometry.ltr/R,...
        'nddtr',geometry.dtr/R,...
        'ndhtr',geometry.htr/R,...
        'ndlvf',geometry.lvf/R,...
        'nddvf',geometry.dvf/R,...
        'ndhvf',geometry.hvf/R,...
        'Gammavf',geometry.Gammavf,...
        'ndllHTP',geometry.llHTP/R,...
        'nddlHTP',geometry.dlHTP/R,...
        'ndhlHTP',geometry.hlHTP/R,...
        'GammalHTP',geometry.GammalHTP,...
        'ndlrHTP',geometry.lrHTP/R,...
        'nddrHTP',geometry.drHTP/R,...
        'ndhrHTP',geometry.hrHTP/R,...
        'GammarHTP',geometry.GammarHTP ...
        );
    
