function Geometry = statGeometry2Geometry (stathelicopter,Svt,cHTP,label,options)

options = parseOptions(options,@statGeometry2GeometryOptions);

xcg                = options.xcg;
epsilony           = options.epsilony;
dtr                = options.dtr;

% funcion que dimensiona la geometria

% Calculated by Rand statistical method.
hf = stathelicopter.Dimensions.heightRotorHead; 

% esto lo voy a poner mejor pero x ahora asi se qda.
h = hf*0.5; 

% Calculated by Rand statistical method.
ltr = stathelicopter.Dimensions.tailRotorArm;

% Calculated by Rand statistical method.
cvt = stathelicopter.Dimensions.cvt; 

% Svt is the vertical fin area. Hypothesis the tailrotor is at the top
% of the vertical fin.
htr = Svt/cvt; 

% Calculated by Rand statistical method.
lvf = stathelicopter.Dimensions.verticalTailSurfaceArm; 

% Hypothesis the vertical fin center is in the middle of the wingspan.
hvf = Svt/cvt*0.5; 

% Calculated by Rand statistical method.
llHTP = stathelicopter.Dimensions.horizontalTailSurfaceArm; 

% Calculated by Rand statistical method.
SHTP = stathelicopter.Dimensions.Sht*0.5;

% Hypothesis the center is in the middle of the wingspan. 
% deberia salir del orden del doble, hipotesis equivocada.
dlHTP = SHTP/cHTP*0.5;


Geometry = struct(...
            'class','geometry',...
            'id',label,...
            'xcg',xcg,...
            'ycg',0,...
            'zcg',0,...
            'epsilonx',0,...
            'epsilony',epsilony,...
            'ls',0,...
            'ds',0,...
            'h',h,...  
            'thetatr',0,...
            'ltr',-ltr,... 
            'dtr',dtr,... % Input.
            'htr',-htr,... 
            'lvf',-lvf,...
            'dvf',0,... % Hypothesis vertical tail surface is centered
            'hvf',-hvf,... 
            'Gammavf',pi/2,...
            'llHTP',-llHTP,... 
            'dlHTP',-dlHTP,... 
            'hlHTP',0,...
            'GammalHTP',0,...
            'lrHTP',-llHTP,... % The Right and left HTP are identical
            'drHTP',dlHTP,...
            'hrHTP',0,...
            'GammarHTP',0 ...
            );


function options = statGeometry2GeometryOptions


options = struct(...
          'xcg',0,...
          'epsilony',0, ...
          'dtr',0 ...
);



