function he = practBo105(atmosphere)

% FIXME Growing structure. Some definitions will be added. To be documented

% Helicopter definition
label = 'practBo105';

% main rotor definition
mainRotor = struct(...
            'class','rigidRotor',...
            'id',label,...
            'active','yes',...
            'R',4.91,...% 
            'e',0.31,...%
            'b',4,...%
            'theta1',-0.15,...
            'cldata',[6.113 0],...% Padfield [6.113 0]
            'cddata',[0.01 0 0],... [0.29395 0.00961 0.0049],... %Padfield [38.66? ? .0074]
            'profile',@cl1cd2,...
            'Omega',44.4,... % 
            'c0',0.27,... %
            'c1',0,... % 
            'IBeta',231.7,...%
            'ITheta',7,...%
            'IZeta',238.7,...% IBeta+ITheta 100000,...% My own
            'xGB',2.1,...% 
            'bm',40.2,...%
            'kBeta',113330,... %
            'k',0 ...
            );

% tail rotor definition
tailRotor = struct(...
            'class','rigidRotor',...
            'id',label,...
            'active','yes',...
            'R',0.95,...%
            'b',2,...% 
            'e',0.,...%
            'theta1',0,...
            'cldata',[5.7 0],...% Padfield [5.7 0]
            'cddata',[0.01 0.0 0.0],...% Padfield [9.5? ? 0.008] [0.29395 0.00961 0.00492]
            'profile',@cl1cd2,...
            'Omega',229,... % 
            'c0',0.179, ... %
            'c1',0, ... %
            'kBeta',1e100,... % rigid
            'k',1 ...
            );

tailRotor = massBlade_mr2inertiaBlade_tr(mainRotor,tailRotor);

% fuselage definition
fuselage = struct(...
            'class','fuselage',...
            'id',label,...
            'active','no',...
            'model',@generalFus,...
            'lf',8.56,...
            'Sp',10,...
            'Ss',12,...
            'kf',1 ...
            );
        
% vertical fin definition
verticalFin = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','no',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',.3,...
            'S',.805,...
            'theta',0.08116,...
            'ks',1 ...
            );
        
% horizontal tail definition
%left
leftHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','no',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',.3,...
            'S',.4015,...
            'theta',0.0698,...
            'ks',1 ...
            );

%right
rightHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','no',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',.3,...
            'S',.4015,...
            'theta',0.0698,...
            'ks',1 ...
            );
        
% transmission        

  

transmission = struct(...
                'transmissionType',@standardTransmission,...
                'etaTmr',0.12,...
                'etaTtr',0.07 ...
             );
        
% geometry definition

geometry = struct(...
            'class','geometry',...
            'id',label,...
            'xcg',0.080033,...
            'ycg',0,...
            'zcg',0,...
            'epsilonx',0,...
            'epsilony',-3*pi/180,...
            'ls',0,...
            'ds',0,...
            'h',1.48,...
            'thetatr',0,...
            'ltr',-6,...
            'dtr',-0.3,...
            'htr',-1.2,... % negative values mean that tr is above the cog
            'lvf',-5.416,...
            'dvf',0,...
            'hvf',-2.04,...
            'Gammavf',pi/2,...
            'llHTP',-4.56,...
            'dlHTP',-.969,...
            'hlHTP',0,...
            'GammalHTP',0,...
            'lrHTP',-4.56,...
            'drHTP',.969,...
            'hrHTP',0,...
            'GammarHTP',0 ...
            );

inertia = struct(...
          'class','inertia',...
          'id',label,...
          'W',2200*9.8,...
          'Ix',1433,...
          'Iy',4973,...
          'Iz',4099,...
          'Ixy',0,...
          'Ixz',660,...
          'Iyz',0 ...
          );


% inertia = struct(...
%           'class','inertia',...
%           'id',label,...
%           'W',2200*9.8,...
%           'Ix',0,...
%           'Iy',0,...
%           'Iz',0,...
%           'Ixy',0,...
%           'Ixz',0,...
%           'Iyz',0 ...
%           );
        
% helicopter definition
he  = struct(...
      'class','rigidHe', ...
      'id',label,...
      'mainRotor',mainRotor,...
      'tailRotor',tailRotor,...
      'fuselage',fuselage,...
      'verticalFin',verticalFin,...
      'leftHTP',leftHTP,...
      'rightHTP',rightHTP,...
      'transmission',transmission,...
      'geometry',geometry,...
      'inertia',inertia ...
);


% atmosphere seems not very clear that it is convenient to be input FIXME
he      = addCharacteristic2he(he,atmosphere);
