function he = Puma(atmosphere)

% FIXME Growing structure. Some definitions will be added. To be documented

% Helicopter definition
label = 'Puma';

% main rotor definition
mainRotor = struct(...
            'class','rigidRotor',...
            'id',label,...
            'active','yes',...
            'R',7.5,...% 
            'e',.64,...%
            'b',4,...%
            'theta1',-.14,...
            'cldata',[5.73 0],...% Padfield 
            'cddata',[0.008 0.00961 0.29395],...[0.01 0 0],... 
            'profile',@cl1cd2,...
            'Omega',27,... % 
            'c0',0.5401,... %
            'c1',0,... % 
            'IBeta',1280,...%
            'ITheta',30,...%
            'IZeta',1310,...% IBeta+ITheta 100000,...% My own
            'xGB',3.22,...% 
            'bm',65.2,...%
            'kBeta',48149,... %
            'k',0 ...
            );

% tail rotor definition
tailRotor = struct(...
            'class','rigidRotor',...
            'id',label,...
            'active','yes',...
            'R',1.56,...%
            'b',5,...% 
            'e',0.,...%
            'theta1',0,...
            'cldata',[5.73 0],...% Padfield [5.7 0]
            'cddata',[0.008 0.00961 0.29395],...
            'profile',@cl1cd2,...
            'Omega',44.4*4.91/.95,... % 
            'c0',0.186, ... %
            'c1',0, ... %
            'IBeta',231.7,...% main rotor
            'ITheta',7,...% main rotor
            'IZeta',238.7,...% main rotor
            'xGB',.475,...% R/2
            'bm',6,...% main rotor bm/(R*c)*(Rt*ct)
            'kBeta',1e100,... %
            'k',1 ...
            );

% fuselage definition
fuselage = struct(...
            'class','fuselage',...
            'id',label,...
            'active','yes',...
            'model',@generalFus,...
            'lf',14,... %Padfield pdf
            'Sp',24.6,... % %Padfield pdf
            'Ss',30.6,... % %Padfield pdf
            'kf',1 ...
            );
        
% vertical fin definition
verticalFin = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',.3,...
            'S',1.395,...%Padfield
            'theta',-0.0175,...%Padfield
            'ks',1 ...
            );
        
% horizontal tail definition
% left
leftHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',.635,...% S/b
            'S',1.34,...%Padfield
            'theta',-0.0262,...%Padfield
            'ks',1 ...
            );

% right
rightHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...
            'type',@get2DStabilizerActions,...
            'c',0,...
            'S',0,...
            'theta',0,...
            'ks',0 ...
            );
        
% geometry definition

geometry = struct(...
            'class','geometry',...
            'id',label,...
            'xcg',0.005,...%Padfield
            'ycg',0,...
            'zcg',0,...
            'epsilonx',0,...
            'epsilony',-0.0873,...%Padfield
            'ls',0,...
            'ds',0,...
            'h',2.157,...%Padfield
            'thetatr',0,...
            'ltr',-9,...%Padfield
            'dtr',.66,...% my own pdf based
            'htr',-1.587,...%Padfield
            'lvf',-9.,...%Padfield
            'dvf',0,...
            'hvf',-1.,...%???????
            'Gammavf',pi/2,...
            'llHTP',-9.,...%Padfield
            'dlHTP',-1.055,...% pdf b/2
            'hlHTP',-1.5,...%~htr
            'GammalHTP',0,...
            'lrHTP',0,...
            'drHTP',0,...
            'hrHTP',0,...
            'GammarHTP',0 ...
            );
        
inertia = struct(...
          'class','inertia',...
          'id',label,...
          'W',5805*9.8,...
          'Ix',9638,...
          'Iy',33240,...
          'Iz',25889,...
          'Ixy',0,...
          'Ixz',2226,...
          'Iyz',0 ...
          );
        
% helicopter definition
he  = struct(...
      'class','rigidHe', ...
      'id',label,...
      'mainRotor',mainRotor,...
      'tailRotor',tailRotor,...
      'fuselage',fuselage,...
      'verticalFin',verticalFin,...
      'leftHTP',leftHTP,...
      'rightHTP',rightHTP,...
      'geometry',geometry,...
      'inertia',inertia ...
);


% atmosphere seems not very clear that it is convenient to be input FIXME
he      = addCharacteristic2he(he,atmosphere);
