function A = ndA2A (ndA,Omega,R)

O = Omega;
OR = Omega*R;
O2 = O*O;
O2R = OR*Omega;
RO = Omega/R;

units = [O O OR O2R O OR O2R OR O2R; ...
         O O OR O2R O OR O2R OR O2R; ...
         RO RO O O2 RO O O2 O O2; ...
         1 1 1 O 1 1 O 1 O; ...
         O O OR O2R O OR O2R OR O2R; ...
         RO RO O O2 RO O O2 O O2; ...
         1 1 1 O 1 1 O 1 O; ...
         RO RO O O2 RO O O2 O O2; ...
         1 1 1 O 1 1 O 1 O; ...
        ];
    
A = units.*ndA;