function B = ndB2B (ndB, Omega, R)

O    = Omega;
OR   = Omega*R;
O2   = O*O;
O2R  = OR*Omega;

units = [O2R O2R O2R O2R; ...
         O2R O2R O2R O2R; ...
         O2  O2  O2  O2 ; ...
         1   1   1   1  ; ...
         O2R O2R O2R O2R; ...
         O2  O2  O2  O2 ; ...
         1   1   1   1  ; ...
         O2  O2  O2  O2 ; ...
         1   1   1   1  ; ...
        ];
    
B = units.*ndB;