function CD = ndConDer2ConDer (ndCD,Omega,R)

O = Omega;
OR = Omega*R;
O2 = O*O;
O2R = OR*Omega;
RO = Omega/R;

units = [O2R O2R O2R O2R; ...
         O2R O2R O2R O2R; ...
         O2 O2 O2 O2; ...
         O2R O2R O2R O2R; ...
         O2 O2 O2 O2; ...
         O2 O2 O2 O2; ...
         ];
    
CD = units.*ndCD;