function SD = ndStaDer2StaDer (ndSD,Omega,R)

O = Omega;
OR = Omega*R;
O2 = O*O;
O2R = OR*Omega;
RO = Omega/R;

units = [O O OR O2R O OR O2R OR O2R; ...
         O O OR O2R O OR O2R OR O2R; ...
         RO RO O O2 RO O O2 O O2; ...
         O O OR O2R O OR O2R OR O2R; ...
         RO RO O O2 RO O O2 O O2; ...
         RO RO O O2 RO O O2 O O2 ...
         ];
    
SD = units.*ndSD;