function [SDnames,CDnames] = SCDnames
% 

SDnames = ...
{'Fx_u' 'Fx_w' 'Fx_omy' 'Fx_The' 'Fx_v' 'Fx_omx' 'Fx_Phi' 'Fx_omz' 'Fx_Psi'  ...
 'Fz_u' 'Fz_w' 'Fz_omy' 'Fz_The' 'Fz_v' 'Fz_omx' 'Fz_Phi' 'Fz_omz' 'Fz_Psi'  ...
 'My_u' 'My_w' 'My_omy' 'My_The' 'My_v' 'My_omx' 'My_Phi' 'My_omz' 'My_Psi'  ...
 'Fy_u' 'Fy_w' 'Fy_omy' 'Fy_The' 'Fy_v' 'Fy_omx' 'Fy_Phi' 'Fy_omz' 'Fy_Psi'  ...
 'Mx_u' 'Mx_w' 'Mx_omy' 'Mx_The' 'Mx_v' 'Mx_omx' 'Mx_Phi' 'Mx_omz' 'Mx_Psi'  ...
 'Mz_u' 'Mz_w' 'Mz_omy' 'Mz_The' 'Mz_v' 'Mz_omx' 'Mz_Phi' 'Mz_omz' 'Mz_Psi'  ...
         }; 
     
CDnames = ...
{'Fx_t0' 'Fx_t1S' 'Fx_t1C' 'Fx_t0tr'  ...
 'Fz_t0' 'Fz_t1S' 'Fz_t1C' 'Fz_t0tr'  ...
 'My_t0' 'My_t1S' 'My_t1C' 'My_t0tr'  ...
 'Fy_t0' 'Fy_t1S' 'Fy_t1C' 'Fy_t0tr'  ...
 'Mx_t0' 'Mx_t1S' 'Mx_t1C' 'Mx_t0tr'  ...
 'Mz_t0' 'Mz_t1S' 'Mz_t1C' 'Mz_t0tr'  ...
         }; 
end