function he = rigidBo105k0(atmosphere)

% FIXME Growing structure. Some definitions will be added. To be documented

%ALVARO: 2015/02/24. There is a diference between Padfield's Of and HEROES
%Of. In the first case, Of is the projection of main rotor reference
%point A, so Padfield's xcg = 0.0163*R = 0.08033 is equivalent to
% HEROEES´s xcg = 0.08033+h*sin(epsilony) = 0.08033+0.0774.
% Similarly ltr, lvf, llHTP and lrHTP are consequently modified.

% Helicopter definition
label = 'rigidBo105';

% main rotor definition
mainRotor = struct(...
            'class','rigidRotor',...
            'active','yes',...
            'id',label,...
            'R',4.91,...% 
            'e',0.31,...%0.31,...
            'b',4,...%
            'theta1',-.14,...
            'cldata',[6.113 0],...% Padfield [6.113 0]
            'cddata',[0.0074 0.00961 0.29395],...[0.01 0 0],... 
            'profile',@cl1cd2,...
            'Omega',44.4,... % 
            'c0',0.27,... %
            'c1',0,... % 
            'IBeta',231.7,...%
            'ITheta',7,...%
            'IZeta',238.7,...% My own 238.7,... % IBeta+ITheta 
            'xGB',2.445,...% (R-0)/2 2.1,... % (R-e)/2
            'bm',40.2,...%
            'kBeta',0,... %
            'k',0 ...
            );

% tail rotor definition
tailRotor = struct(...
            'class','rigidRotor',...
            'id',label,...
            'active','yes',...
            'R',.95,...%
            'b',2,...% 
            'e',0.,...%
            'theta1',0,...
            'cldata',[5.7 0],...% Padfield [5.7 0]
            'cddata',[0.008 0.00961 0.29395],...
            'profile',@cl1cd2,...
            'Omega',2220*2*pi/60,... % 
            'c0',0.18, ... %
            'c1',0, ... %
            'IBeta',1.805,...% bm/3*R^2
            'ITheta',0.0648,...%
            'IZeta',1.8698,...% 
            'xGB',.475,...% R/2
            'bm',6,...% main rotor bm/(R*c)*(Rt*ct)
            'kBeta',1e100,... %
            'k',1 ...
            );

% fuselage definition
fuselage = struct(...
            'class','fuselage',...
            'id',label,...
            'active','yes',...
            'model',@generalFus,...@PadBo105Fus,...
            'lf',8.56,...
            'Sp',7.5,... 
            'Ss',8.3,... 
            'kf',1 ...
            );
        
% vertical fin definition
verticalFin = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...@vfBo105Padf,...
            'type',@get2DStabilizerActions,...
            'c',.3,...
            'S',.805,...
            'theta',0.08116,...
            'ks',1 ...
            );
        
% horizontal tail definition
% left
leftHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...@HTPBo105Padf,...
            'type',@get2DStabilizerActions,...
            'c',.4,...
            'S',.4015,...
            'theta',0.0698,...
            'ks',1 ...
            );

% right
rightHTP = struct(...
            'class','stabilizer',...
            'id',label,...
            'active','yes',...
            'airfoil',@naca0012,...@HTPBo105Padf,...
            'type',@get2DStabilizerActions,...
            'c',.4,...
            'S',.4015,...
            'theta',0.0698,...
            'ks',1 ...
            );
        
% transmission        

  

transmission = struct(...
                'transmissionType',@standardTransmission,...
                'etaTmr',0.12,...
                'etaTtr',0.07 ...
             );

% grometry definition

geometry = struct(...
            'class','geometry',...
            'id',label,...
            'xcg',0.08033+0.0774,...%ALVARO
            'ycg',0,...
            'zcg',0,...
            'epsilonx',0,...
            'epsilony',-0.0523,...
            'ls',0,...
            'ds',0,...
            'h',1.48,...
            'thetatr',0,...
            'ltr',-6+0.0774,...
            'dtr',-.3,...
            'htr',-1.72+0.0774,...%ALVARO
            'lvf',-5.416+0.0774,...%ALVARO
            'dvf',0,...
            'hvf',-0.86,...
            'Gammavf',pi/2,...
            'llHTP',-4.56+0.0774,...
            'dlHTP',-.969,...
            'hlHTP',0,...
            'GammalHTP',0,...
            'lrHTP',-4.56+0.0774,...
            'drHTP',.969,...
            'hrHTP',0,...
            'GammarHTP',0 ...
            );
        
inertia = struct(...
          'class','inertia',...
          'id',label,...
          'W',2200*9.8,...
          'Ix',1433,...
          'Iy',4973,...
          'Iz',4099,...
          'Ixy',0,...
          'Ixz',660,...
          'Iyz',0 ...
          );
        
% helicopter definition
he  = struct(...
      'class','rigidHe', ...
      'id',label,...
      'mainRotor',mainRotor,...
      'tailRotor',tailRotor,...
      'fuselage',fuselage,...
      'verticalFin',verticalFin,...
      'leftHTP',leftHTP,...
      'rightHTP',rightHTP,...
      'transmission',transmission,...
      'geometry',geometry,...
      'inertia',inertia ...
);


% atmosphere seems not very clear that it is convenient to be input FIXME
he      = addCharacteristic2he(he,atmosphere);
