
F(4) =  (-y_cg+dy_ad-sin(epsilon_x)*h_ad)*CTinF-(-z_cg-cos(epsilon_x)*cos(epsilon_y)*h_ad)*CYinF+CM_RPXinF+...
(-y_cg+dRA_ad)*CF_RAZinF-(-z_cg+lRAV_ad)*CF_RAYinF+CM_RAXinF + ...
-y_cg*CD_ZFinF+z_cg*CD_YFinF+...
(-y_cg+dEHI_ad)*CF_ZEHIinF-(-z_cg+lEVH_ad)*CF_YEHIinF+CM_EHIXinF...
(-y_cg+dEHD_ad)*CF_ZEHDinF-(-z_cg+lEHV_ad)*CF_YEHDinF+CM_EHDXinF...
-y_cg*CF_ZEVinF-(-z_cg+lEVV_ad)*CF_YEVinF+CM_EVXinF;



F(5) =  (-z_cg-cos(epsilon_x)*cos(epsilon_y)*h_ad)*CHinF-(-x_cg+dx_ad-cos(epsilon_x)*sin(epsilon_y)*h_ad)*CTinF+CM_RPYinF+...
(-z_cg+lRAV_ad)*CF_RAXinF-(-x_cg+lRAH_ad)*CF_RAZinF+CM_RAYinF+...
-z_cg*CD_XFinF+x_cg*CD_ZFinF+...
(-z_cg+lEVH_ad)*CF_XEHIinF-(-x_cg+lEHH_ad)*CF_ZEHIinF+CM_EHIYinF...
(-z_cg+lEHV_ad)*CF_XEHDinF-(-x_cg+lEHH_ad)*CF_ZEHDinF+CM_EHDYinF...
(-z_cg+lEVV_ad)*CF_XEVinF-(-x_cg+lEVH_ad)*CF_ZEVinF+CM_EVYinF;



F(6) =  (-x_cg+dx_ad-cos(epsilon_x)*sin(epsilon_y)*h_ad)*CYinF-(-y_cg+dy_ad-sin(epsilon_x)*h_ad)*CHinF+CM_RPZinF+...
(-x_cg+lRAH_ad)*CF_RAYinF-(-y_cg+dRA_ad)*CF_RAXinF+CM_RAZinF+...
-x_cg*CD_YFinF+y_cg*CD_XFinF+...
(-x_cg+lEHH_ad)*CF_YEHIinF-(-y_cg+dEHI_ad)*CF_XEHIinF+CM_EHIZinF...
(-x_cg+lEHH_ad)*CF_YEHDinF-(-y_cg+dEHD_ad)*CF_XEHDinF+CM_EHDZinF...
(-x_cg+lEVH_ad)*CF_YEVinF+y_cg*CF_XEVinF+CM_EVZinF;

