function io = dimensioning04(mode)

% Get atmosphere
atm        = getISA;

% Get design requirements
dr        = cesarDR;

% Select engine and number of engines
numEngines = 2;
engine     = Allison250C28C(atm,numEngines);

% Transform design requirements and engine data to statistical helicopter
stathe     = desreq2stathe(dr,engine);


% vertical fin surface
Svt = .805;

% horizontal tail plane chord
cHTP = .4;

%--------------------------------------------------------------------------
itest = 0;
%--------------------------------------------------------------------------
% Test number 1
% empty option cell just to test default options
itest = itest + 1;
disp(strcat('Testing stathe2rigidhe-> Test number',num2str(itest)));

optStatHe = struct(...
      'mainRotor',[],...
      'tailRotor',[],...
      'fuselage',[],...
      'verticalFin',[],...
      'leftHTP',[],...
      'rightHTP',[],...
      'geometry',[] ...
);

rigidhe1 = stathe2rigidhe(stathe,atm,cHTP,Svt,optStatHe);

% % %--------------------------------------------------------------------------
% % % Test number 2 THIS TEST DOES NOT WORK BECAUSE OF PARSE_PV_PAIRS
% % % Define options structure for the main rotor to override default options 
% % % of rotor options using only the parameter to be overriden
% % itest = itest + 1;
% % disp(strcat('Testing gethestat2hedim-> Test number',num2str(itest)));
% % 
% % optMR   = struct(...
% %           'kBeta', 113330 ...
% % );
% % 
% % optStatHe = struct(...
% %       'mainRotor',optMR,...
% %       'tailRotor',[],...
% %       'verticalFin',[],...
% %       'leftHTP',[],...
% %       'rightHTP',[],...
% %       'geometry',[] ...
% % );
% % hedim2 = gethestat2hedim(hestat,atm,Svt,cHTP,Ix,Iy,Iz,Ixz,optStatHe);

%--------------------------------------------------------------------------
% Test number 3
% Define options structure for the main rotor to override default options 
% of rotor options but now with the full default parameters
itest = itest + 1;
disp(strcat('Testing stathe2rigidhe-> Test number',num2str(itest)));

optMR   = struct(...
          'e',0.0,...
          'theta1',-8*pi/180,...
          'cldata',[6.113 0],...
          'cddata',[0.0074 0.00961 0.29395],...
          'kBeta', 113330 ...
);

optStatHe = struct(...
      'mainRotor',optMR,...
      'tailRotor',[],...
      'verticalFin',[],...
      'leftHTP',[],...
      'rightHTP',[],...
      'geometry',[] ...
);


rigidhe2 = stathe2rigidhe(stathe,atm,Svt,cHTP,optStatHe);


io = 1;

