function sd  = heroesDirs

sr            = heroesRoot;


sd  = { ...
       fullfile(sr,'atmosphere'), ...
       fullfile(sr,'common'), ...
       fullfile(sr,'dimensioning'), ...
       fullfile(sr,'dimensioning',filesep,'ndarc'), ...
       fullfile(sr,'dimensioning',filesep,'rand'), ...
       fullfile(sr,'energy'), ...
       fullfile(sr,'flightDynamics'), ...
       fullfile(sr,'geometry'), ...
       fullfile(sr,'heroesData'), ...
       fullfile(sr,'heroesData',filesep,'airfoil'), ...
       fullfile(sr,'heroesData',filesep,'airfoil3D'), ...
       fullfile(sr,'heroesData',filesep,'desreq'), ...
       fullfile(sr,'heroesData',filesep,'energyHe'), ...
       fullfile(sr,'heroesData',filesep,'engine'), ...
       fullfile(sr,'heroesData',filesep,'fc'), ...
       fullfile(sr,'heroesData',filesep,'fuselage'), ...
       fullfile(sr,'heroesData',filesep,'Gazelle'), ...
       fullfile(sr,'heroesData',filesep,'rigidHe'), ...
       fullfile(sr,'heroesData',filesep,'rigidNLHe'), ...
       fullfile(sr,'heroesData',filesep,'transmission'),...
       fullfile(sr,'heroesData',filesep,'validationData'), ...
       fullfile(sr,'heroesData',filesep,'validationData',filesep,'Bo105'), ...
       fullfile(sr,'heroesData',filesep,'validationData',filesep,'Gazelle'), ...
       fullfile(sr,'heroesData',filesep,'validationData',filesep,'Lynx'), ...
       fullfile(sr,'heroesData',filesep,'validationData',filesep,'Padfield95'), ...
       fullfile(sr,'heroesData',filesep,'validationData',filesep,'Puma'), ...
       fullfile(sr,'heroesDataTools'), ...
       fullfile(sr,'heroesDoc'), ...
       fullfile(sr,'heroesDoc',filesep,'heroesDemos'), ...
       fullfile(sr,'heroesDoc',filesep,'icon'), ...
       fullfile(sr,'heroesOptions'), ...
       fullfile(sr,'heroesPost'), ...
       fullfile(sr,'heroesTest'), ...
       fullfile(sr,'inducedVelocity'), ...
       fullfile(sr,'mission'), ...
       fullfile(sr,'mission',filesep,'segmentBuilders'), ...
       fullfile(sr,'mission',filesep,'segmentSolvers'), ...
       fullfile(sr,'oec'), ...
       fullfile(sr,'qfd'), ...
       fullfile(sr,'stability'), ...
       fullfile(sr,'trim'), ...
       fullfile(sr,'trim',filesep,'fuselage'), ...
       fullfile(sr,'trim',filesep,'interference'), ...
       fullfile(sr,'trim',filesep,'rotor'), ...
       fullfile(sr,'trim',filesep,'rotorNL'), ...
       fullfile(sr,'trim',filesep,'stabilizer') ...
};

