function A = setEpowerStateVars(io)

if io == 1
    yvars = {'P','Pi','Pf','Pcd0',...
             'Pg'};
    ylabs = {'$P$ [MW]','$P_{i}$ [MW]','$P_{f}$ [MW]','$P_{cd0}$ [MW]' ...
             '$P_{g}$ [MW]'};
    yunits= [1e-6,1e-6,1e-6,1e-6,1e-6];
elseif io > 1
    yvars = {'P','Pi','Pf','Pcd0',...
             'Pg','vi'};
    ylabs = {'$P$ [MW]','$P_{i}$ [MW]','$P_{f}$ [MW]','$P_{cd0}$ [MW]' ...
             '$P_{g}$ [MW]','$v_i$ [m/s]'};
    yunits= [1e-6,1e-6,1e-6,1e-6,1e-6,1];
end

xvar  = {'Vh'};
xlab  = {'$V_h$ [m/s]'};

 A     = struct(...
        'xvar',{xvar},...
        'xlab',{xlab},...
        'xunit',1,...
        'yvars',{yvars},...
        'ylabs',{ylabs},...
        'yunits',yunits...
 );
