function opts = setHeroesPlotOptions
%  SETHEROESPLOTOPTIONS Defines the default plot options of HEROES
%     
%  OPTIONS = SETHEROESPLOTOPTIONS returns the default plot options
%  structure of HEROES, OPTIONS. The default structure is:
%   defaultVars: 'yes'
%          mode: 'thin'
%          mark: {'r-'  'b-.'  'k:' [until 13 marker sets] 'r-<'}
%         lines: {'b-','k-','r-' [until 54 line sets]} 'g--'}
%        format: {'epsc'  'pdf'  'fig'}
%        prefix: 'no'
%     closePlot: 'no'
%     titleplot:,[]
%
%  defaultVars - Default variables [ 'yes' | vars struct ] 
%       -- FIX DOCS --
%
%  mode - Plot mode  [ 'thick' | {'thin'} ]
%     This string sets the default font size and line width of the plots
%     The mode 'thin' is MATLAB default value. The mode 'thick' is set
%     by the script SETPLOT (see setPlot) and the default font size and
%     line widths are bigger than the ones of 'thin'
%
%  mark - Markers for plot series  [ cell of strings ]
%     This cell of strings sets the markers used by default for the plot
%     series (until 13 series)
%
%  lines - Markers for plot series  [ cell of strings ]
%     This cell of strings sets the markers used by default for the plot
%     series (more than 13 series)
%
%
%  format - Output file format  [ cell of valid MATLAB formats]
%     This cell of strings sets the desired output format. By default is
%     set to {'epsc'  'pdf'  'fig'}. In the case that output is saved 
%     then by default every figure will be saved in these three formats
%     See also print to valid formats
%
%  prefix - Prefix to be appended to the name of the output file [string]
%     This string is set to 'no' meaning that by default the will not 
%     be output files. In the case that this prefix is set to other value
%     than 'no' the plots will be saved with names formed by the prefix
%     value plus the corresponding plotted variable.
%
%  closeplot - Switch to close the plots [yes | {no}]
%     This string specifies whether the plots are to be closed or not.
%
%  titleplot - Title string  [string | {[]}]
%     This string is added as title text to the plots.
%
%  plot3dMethod - matlab 3d plot function [ {@contour} | @ surfc ] 
%
%  labels -  switch to add labels to contour plots [ {'yes'} | 'no' ]
%
%  nlevels - number of levels for contour plots [ {10} | integer ]
%  colormap - matlab color map [ {'jet'} | ... | pink | autum ]
%  colorbar - switch to add color bar [ {'yes'} | no ]
%  polarPlot - switch for polar plots [ {'no'} | 'yes' ]
%  plot2dMode - mode for 2D plots [ {'oneFigure'} | 'nFigures' ] 
%  plot3dMode - mode for 3D plots [ {'bidimensional'} | 'parametric' ] 
%
%  gridOn - switch to add grid to plots [ {'yes'} | 'no' ]
%
%  clockwisePolar - switch to control the variation of polar angle [ {'yes'} | 'no' ]
%    This string is set to 'no' meaning that the variation of the polar
%    angle is clockwise which corresponds to the standard rotation of
%    british helicopters.
%
fmt    = {'epsc','pdf','fig'};

mark   = {'k-o','k-.','k--','k-s','k-o','k-^',...
          'k-d','k:.','k-*','k-+',...
          'k-v','k->','k-<'...
};

lines  = { ...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--',...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--',...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--',...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--',...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--',...
          'k-','b-','r-','m-','g-',...
          'k-.','b-.','r-.','m-.','g-.',...
          'k--','b--','r--','m--','g--'...
         };

prefix     = 'no';
closePlot  = 'no';

opts  = struct(...
               'polarPlot','no',...
               'clockwisePolar','no',...
               'plot3dMode','bidimensional',...
               'plot2dMode','oneFigure',...
               'plot3dMethod',@contour,...
               'contourLevelList',[],...
               'labels','off',...
               'nlevels',10,...
               'colormap','jet',...
               'colorbar','yes',...
               'gridOn','yes',...
               'defaultVars','yes',...
               'mode','thin',...
               'mark',{mark},...
               'lines',{lines},...
               'format',{fmt},...
               'prefix',prefix,...
               'closePlot',closePlot, ...
               'titleplot',[]...
              );
