function X = setTrimStateVars


r2d    = 180/pi;

xvar   = {'VOR'};
xlab   = {'V/(\Omega R) [-]'};
xunit  = 1;
yvars  = {'Psi' 'Theta' 'Phi' ...
         'theta0' 'theta1C' 'theta1S' ...
         'theta0tr' ...
         'beta0' 'beta1C' 'beta1S' ...
         'lambda0' 'lambda1C' 'lambda1S' ...
         'CT0' 'CT1C' 'CT1S' ...                  
         'beta0tr' 'beta1Ctr' 'beta1Str' ...
         'lambda0tr' 'lambda1Ctr' 'lambda1Str' ...
         'CT0tr' 'CT1Ctr' 'CT1Str' ...
         'omega' 'CW' ...
         'VOR' 'gammaT' 'betaT' ...
         'uTOR' 'vTOR' 'wTOR' ...
         'ueOR' 'veOR' 'weOR' ...
         'betaf0' 'alphaf0' ...
         'omxad' 'omyad' 'omzad' ...
         'omegaAdzT' 'cs' ... 
         };
     
ylabs  = {'\Psi [^o]' '\Theta [^o]' '\Phi [^o]' ...
         '\theta_{0} [^o]' '\theta_{1C} [^o]' '\theta_{1S} [^o]' ...
         '\theta_{0tr} [^o]' ...
         '\beta_{0} [^o]' '\beta_{1C} [^o]' '\beta_{1S} [^o]' ...
         '\lambda_{0} [-]' '\lambda_{1C} [-]' '\lambda_{1S} [-]' ...
         'C_{T0} [-]' 'C_{T1C} [-]' 'C_{T1S} [-]' ...                  
         '\beta_{0tr} [^o]' '\beta_{1Ctr} [^o]' '\beta_{1Str} [^o]' ...
         '\lambda_{0tr} [-]' '\lambda_{1Ctr} [-]' '\lambda_{1Str} [-]' ...
         '\CT_{0tr} [-]' '\C_{T1Ctr} [-]' '\C_{T1Str} [-]' ...
         '\Omega/\Omega_{R} [-]' 'C_{W} [-]' ...
         'V/(\Omega R) [-]' '\gamma_{T} [^o]' '\beta_{T} [^o]' ...
         'u_{T}\Omega R [-]' 'v_{T}\Omega R [-]' 'w_{T}\Omega R [-]' ...
         'u_{e}/\Omega R [-]' 'v_{e}\Omega R [-]' 'w_{e}\Omega R [-]' ...
         '\beta_{f0 [^o]' '\alpha_{f0 [^o]' ...
         '\omega_{x}/\Omega [-]' 'omega_{y}/\Omega [-]' 'omega_{z}/\Omega [-]' ...
         'omega_{zT}/\Omega [-]' 'cs [-]' ... 
         };

%ylabs  = {'\Theta [^o]' '\Phi [^o]' ...
%         '\theta_0 [^o]' '\theta_{1C} [^o]' '\theta_{1S} [^o]' ...
%         '\theta_{0tr} [^o]' ...
%        '\beta_0 [^o]' '\beta_{1C} [^o]' '\beta_{1S} [^o]'...
%        '\lambda_0 [-]' '\lambda_{1C} [-]' '\lambda_{1S} [-]' ...
%        'C_{T} [-]'};
     
  yunits  = {r2d r2d r2d ...
            r2d r2d r2d ...
            r2d ...
            r2d r2d r2d ...
            1 1 1 ...
            1 1 1 ...                  
            r2d r2d r2d ...
            1 1 1 ...
            1 1 1 ...
            1 1 ...
            1 r2d r2d ...
            1 1 1 ...
            1 1 1 ...
            r2d r2d ...
            1 1 1 ...
            1 1 ... 
            };   

%yunits = [r2d r2d r2d r2d r2d r2d r2d r2d r2d 1 1 1 1];

X      = struct(...
         'xvar',{xvar},...
         'xlab',{xlab},...
         'xunit',xunit,...
         'yvars',{yvars},...
         'ylabs',{ylabs},...
         'yunits',yunits...
);

