function y = AFDD(desreq,mainRotor,tailRotor,dimensions,performances,weights,engine)

alightingGearWeight = AlightingGearWeight(desreq, weights);
rotorGroupWeight = RotorGroupWeight(desreq,mainRotor);
driveSystemWeight = DriveSystemWeight(desreq,performances, rotorGroupWeight,dimensions, mainRotor,engine);
empennageGroupWeight = EmpennageGroupWeight(desreq,mainRotor,tailRotor,dimensions,performances);
engineSystemWeight = EngineSystemWeight(desreq, performances, engine);
engineSectionWeight = EngineSectionWeight(desreq, engine);
flightControlsWeight = FlightControlsWeight(desreq, mainRotor,dimensions);
fuelSystemWeight = FuelSystemWeight(desreq,engine,weights);
fuselageGroupWeightHello = FuselajeGroupWeightHello(desreq,dimensions);
hydraulicGroupWeight = HydraulicGroupWeight(desreq, flightControlsWeight);
aircraftFlyawayCost = AircraftFlyawayCost(desreq,mainRotor,weights,engine);
directOperatingCost = DirectOperatingCost(desreq,weights,engine,aircraftFlyawayCost);

y = struct(...
    'AlightingGearWeight', alightingGearWeight,...
    'DriveSystemWeight', driveSystemWeight,...
    'EmpennageGroupWeight', empennageGroupWeight,...
    'EngineSectionWeight', engineSectionWeight,...
    'EngineSystemWeight', engineSystemWeight,...
    'FlightControlsWeight', flightControlsWeight,...
    'FuelSystemWeight', fuelSystemWeight,...
    'FuselajeGroupWeightHello', fuselageGroupWeightHello,...
    'HydraulicGroupWeight', hydraulicGroupWeight,...
    'RotorGroupWeight', rotorGroupWeight,...
    'AircraftFlyawayCost',aircraftFlyawayCost,...
    'DirectOperatingCost', directOperatingCost);
end

