function eng = 250-C30G(atmosphere,numEngines)
%
% Author: Marina Hierro marina.hierro.tobar@alumnos.upm.es
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell 230 (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'250-C30G'},...
                    'weight',114.7608*g,...
                    'lenght',1.09728,...
                     'width',0.5588,...
                    'height',0.65278,...
                      'Snac',2.658885005,...
              'PowerTakeOff',484.705e3,...
    'PowerMaximumContinuous',415.3549e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',9158,...
                       'PSFC',0.000100031555555556e-3 ...
);


eng  = addEnginePerformance(eng,atmosphere);
