function eng = AE1007(atmosphere,numEngines)
%
% Author: Sergio Nadal s.nadal@alumnos.upm.es
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
eng = struct( ...
               'helicopters',{'Bell-Boeing V22 Osprey (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'AE 1007'},...
                    'weight',440.4460*g,...
                    'lenght',1.5240,...
                     'width',0.7544,...
                    'height',0.8661,...
                      'Snac',4.9393,...
              'PowerTakeOff',4.54877e+06,...
    'PowerMaximumContinuous',4.25274e+06,...
                  'OmegaRPM',15000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'SPC',7.20e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);