function eng = AL5512(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'BV234 & BV234LR (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'AL5512'},...
                    'weight',353.808*g,...
                    'lenght',1.196811,...
                     'width',0.6161925,...
                    'height',0.6161925,...
                      'Snac',2.9498638,...
              'PowerTakeOff',3038.7275e3,...
    'PowerMaximumContinuous',2218.4575e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',14750,...
                       'PSFC',9.1751917e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

