function eng = Allison250C28C(atmosphere,numEngines)
%
% Author: César García cesar.garcia.lozano@alumnos.upm.es
% Date: 29/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Bo 105 (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'250-C28C'},...
                    'weight',107.05*g,...
                    'lenght',1.1011,...
                     'width',0.5588,...
                    'height',0.6472,...
                      'Snac',2.658885005,...
              'PowerTakeOff',372.850e3,...
    'PowerMaximumContinuous',372.850e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',6016,...
                      'PSFC',1.21657503e-7 ...
);


eng  = addEnginePerformance(eng,atmosphere);
