function eng = Ardiden1H1(atmosphere,numEngines)
%
% Author: Francisco Cristobal Serrano fco.serrano.guzman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'DHRUV (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Ardiden1H1'},...
                    'weight',198*g,...
                    'lenght',1.25,...
                     'width',0.694,...
                    'height',0.519,...
                      'Snac',3.0325,...
              'PowerTakeOff',1023.85e3,...
    'PowerMaximumContinuous',858.3007e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.77272e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

