function eng = Arriel2S1(atmosphere,numEngines)
%
% Author: Francisco Cristobal Serrano fco.serrano.guzman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Sikorsky S76 C+ (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel2S1'},...
                    'weight',127.9152*g,...
                    'lenght',1.01346,...
                     'width',0.46228,...
                    'height',0.71374,...
                      'Snac',2.3836985,...
              'PowerTakeOff',638.319e3,...
    'PowerMaximumContinuous',586.8659e3,...
                  'OmegaRPM',6409,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.1245e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

