function eng = Arriel1S1(atmosphere,numEngines)
%
% Author: Cesar Garcia cesar.garcia.lozano@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Sikorsky S76 A++ (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel1S1'},...
                    'weight',121.111*g,...
                    'lenght',1.5392,...
                     'width',0.4623,...
                    'height',0.7874,...
                      'Snac',3.8471,...
              'PowerTakeOff',539.141e3,...
    'PowerMaximumContinuous',540.632e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.58073e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

