function eng = Arrius1M(atmosphere,numEngines)
%
% Author: Sergio Nadal s.nadal@alumnos.upm.es
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS 555 N (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arrius 1 M'},...
                    'weight',113.854*g,...
                    'lenght',1.1582,...
                     'width',0.3607,...
                    'height',0.5867,...
                      'Snac',2.1947,...
              'PowerTakeOff',357.190e+03,...
    'PowerMaximumContinuous',302.754+03,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'SPC',9.40e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);