function eng = Arriel2C2CG(atmosphere,numEngines)
%
% Author: Francisco Cristobal Serrano fco.serrano.guzman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter HH65C (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel2C2CG'},...
                    'weight',127.9152*g,...
                    'lenght',1.01346,...
                     'width',0.46228,...
                    'height',0.57658,...
                      'Snac',2.1056861,...
              'PowerTakeOff',697.23e3,...
    'PowerMaximumContinuous',474.2652e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.04001e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

