function eng = Arriel2C(atmosphere,numEngines)
%
% Author: Francisco Cristobal Serrano fco.serrano.guzman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS365 N3 (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel2C'},...
                    'weight',127.9152*g,...
                    'lenght',1.1811,...
                     'width',0.46228,...
                    'height',0.61722,...
                      'Snac',2.5499949,...
              'PowerTakeOff',634.591e3,...
    'PowerMaximumContinuous',596.56e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.25968e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

