function eng = Arriel1E2(atmosphere,numEngines)
%
% Author: Cesar Garcia cesar.garcia.lozano@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter EC145 (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel1E2'},...
                    'weight',125.194*g,...
                    'lenght',1.1861,...
                     'width',0.4623,...
                    'height',0.6934,...
                      'Snac',2.7417,...
              'PowerTakeOff',550.327e3,...
    'PowerMaximumContinuous',516.024e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.69901e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

