function eng = Arrius2F(atmosphere,numEngines)
%
% Author: Sergio Nadal s.nadal@alumnos.upm.es
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
eng = struct( ...
               'helicopters',{'Eurocopter EC120 (1)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arrius 1 M'},...
                    'weight',102.967*g,...
                    'lenght',1.3513,...
                     'width',0.4597,...
                    'height',0.6731,...
                      'Snac',3.0616,...
              'PowerTakeOff',375.833e+03,...
    'PowerMaximumContinuous',335.565e+03,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'SPC',9.40e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);