function eng = Arrius_2K2(atmosphere,numEngines)
%
% Author: Alvaro Moreno alvaro.msacristan@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Agusta A109 LUH (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arrius 2K2'},...
                    'weight',115.2144*g,...
                    'lenght',0.97282,...
                     'width',0.4699,...
                    'height',0.63754,...
                      'Snac',2.1546795616,...
              'PowerTakeOff',533.9212e+03,...
    'PowerMaximumContinuous',454.1313e+03,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8,90483611111111e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

