function eng = Arriel_1_B(atmosphere,numEngines)
%
% Author: Alvaro Moreno alvaro.msacristan@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS 350 BA (1)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel 1 B'},...
                    'weight',114.3072*g,...
                    'lenght',1.19888,...
                     'width',0.46228,...
                    'height',0.5969,...
                      'Snac',2.5396594368,...
              'PowerTakeOff',477.9937e+03,...
    'PowerMaximumContinuous',440.7087e+03,...
                  'OmegaRPM',5976,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.00538472222222e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);

