function eng = Arriel1D(atmosphere,numEngines)
%
% Author: Cesar Garcia cesar.garcia.lozano@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS350 B1 (1)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arriel1D'},...
                    'weight',122.5*g,...
                    'lenght',1.1989,...
                     'width',0.4623,...
                    'height',0.5969,...
                      'Snac',2.5397,...
              'PowerTakeOff',510.059e3,...
    'PowerMaximumContinuous',449.657e3,...
                  'OmegaRPM',5976,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.80039e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

