function eng = Arrius_2B1A_1(atmosphere,numEngines)
%
% Author: Alvaro Moreno alvaro.msacristan@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter EC135 t1 (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Arrius 2B1A-1'},...
                    'weight',113.8536*g,...
                    'lenght',1.18364,...
                     'width',0.51816,...
                    'height',0.69088,...
                      'Snac',2.8621362112,...
              'PowerTakeOff',463.0797e+03,...
    'PowerMaximumContinuous',413.8635e+03,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8.88793888888889e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

