function eng = CT58_140(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Boeing-Vertol V107 (2),Sikorsky S-61 (2)'},...
              'manufacturer',{'General Electric'},...
                     'model',{'CT58-140'},...
                    'weight',154.224*g,...
                    'lenght',1.42296,...
                     'width',0.40656,...
                    'height',0.40656,...
                      'Snac',2.31407,...
              'PowerTakeOff',1043.98e+03,...
    'PowerMaximumContinuous',932.125e+03,...
                  'OmegaRPM',19500,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.030731e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);

