function eng = CT7_8A(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Sikorsky S-92 (2)'},...
              'manufacturer',{'General Electric'},...
                     'model',{'CT7-8A'},...
                    'weight',245.8512*g,...
                    'lenght',1.240008,...
                     'width',0.66066,...
                    'height',0.63525,...
                      'Snac',3.2138775,...
              'PowerTakeOff',1.96417e+06,...
    'PowerMaximumContinuous',1.608479e+06,...
                  'OmegaRPM',21945,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.6375444e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

