function eng = CT7_6A(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'EH Industries EH101 (3)'},...
              'manufacturer',{'General Electric'},...
                     'model',{'CT7-6A'},...
                    'weight',223.6248*g,...
                    'lenght',1.1943,...
                     'width',0.6352,...
                    'height',0.6352,...
                      'Snac',3.0346,...
              'PowerTakeOff',1.4914e+06,...
    'PowerMaximumContinuous',1.2811e+06,...
                  'OmegaRPM',20463,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.6713e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

