function eng = CT7_2A(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell 214ST (2)'},...
              'manufacturer',{'General Electric'},...
                     'model',{'CT7-2A'},...
                    'weight',194.5944*g,...
                    'lenght',1.1943,...
                     'width',0.6352,...
                    'height',0.6352,...
                      'Snac',3.0346,...
              'PowerTakeOff',1.2118e+06,...
    'PowerMaximumContinuous',1.1894e+06,...
                  'OmegaRPM',21000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',8.0093e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

