function eng = CTS800_4K(atmosphere,numEngines)
%
% Author: sergio Fernandez sergio.fernandezr@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Shimaywa US2 (1)'},...
              'manufacturer',{'LHTEC'},...
                     'model',{'CTS800_4K'},...
                    'weight',163.296*g,...
                    'lenght',0.858858,...
                     'width',0.805497,...
                    'height',0.55902,...
                      'Snac',2.3438527,...
              'PowerTakeOff',991.035e3,...
    'PowerMaximumContinuous',920.1938e3,...
                  'OmegaRPM',6402,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.77272e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);