function eng = Gem_42_1(atmosphere,numEngines)
%
% Author: Hector Fernandez hector.fdotu@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Agusta Westland Lynx (2), Agusta Westland A129 Mangusta (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'Gem 42-1'},...
                    'weight',183.2544*g,...
                    'lenght',1.09728,...
                     'width',0.57404,...
                    'height',0.5969,...
                      'Snac',2.569698086,...
              'PowerTakeOff',745.7e3,...
    'PowerMaximumContinuous',663.673e3,...
                  'OmegaRPM',6164,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',8.61758e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

