function eng = Gem_60_3MK530(atmosphere,numEngines)
%
% Author: Hector Fernandez hector.fdotu@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Agusta Westland Lynx (2), Agusta Westland A129 Mangusta (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'Gem 60-3MK530'},...
                    'weight',191*g,...
                    'lenght',1.0922,...
                     'width',0.5715,...
                    'height',0.5969,...
                      'Snac',2.55225296,...
              'PowerTakeOff',879.926e3,...
    'PowerMaximumContinuous',857.555e3,...
                  'OmegaRPM',6300,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',8.61758e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

