function eng = HTS900(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell ARH (1)'},...
              'manufacturer',{'Honeywell Defense and Space'},...
                     'model',{'HTS900'},...
                    'weight',142.884*g,...
                    'lenght',0.91476,...
                     'width',0.5082,...
                    'height',0.60984,...
                      'Snac',2.949863,...
              'PowerTakeOff',744.2086e+03,...
    'PowerMaximumContinuous',664.4187e+03,...
                  'OmegaRPM',6317,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8.8879389e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

