function eng = LTS101_750C_1(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell 222B, UT (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-750C-1'},...
                    'weight',110.6784*g,...
                    'lenght',0.7955871,...
                     'width',0.574266,...
                    'height',0.5120115,...
                      'Snac',1.728456732,...
              'PowerTakeOff',510.0588e+03,...
    'PowerMaximumContinuous',486.9421e+03,...
                  'OmegaRPM',9545,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.800e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

