function eng = LTS101_700D_2(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'EurocopterAS350B2'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-700D-2'},...
                    'weight',120.204*g,...
                    'lenght',0.8042265,...
                     'width',0.4921917,...
                    'height',0.630168,...
                      'Snac',1.805262827,...
              'PowerTakeOff',545.8524e+03,...
    'PowerMaximumContinuous',484.705e+03,...
                  'OmegaRPM',6780,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.631e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

