function eng = LTS101_850B_2(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter HH-65A (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-850B-2'},...
                    'weight',122.9256*g,...
                    'lenght',0.8222676,...
                     'width',0.5046426,...
                    'height',0.6271188,...
                      'Snac',1.86122146,...
              'PowerTakeOff',581.646e+03,...
    'PowerMaximumContinuous',556.2922e+03,...
                  'OmegaRPM',6780,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.631e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

