function eng = LTS101_600A_3A(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'EurocopterAS350B (1), EurocopterAS350D (1), EurocopterAS350BA (1))'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-600A-2/-3'},...
                    'weight',120.204*g,...
                    'lenght',0.8019396,...
                     'width',0.4921917,...
                    'height',0.630168,...
                      'Snac',1.800129,...
              'PowerTakeOff',484.705e+03,...
    'PowerMaximumContinuous',466.0625e+03,...
                  'OmegaRPM',6085,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.631e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

