function eng = LTS101_650B_1(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter, BK-117A (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-650B-1'},...
                    'weight',121.5648*g,...
                    'lenght',0.7889805,...
                     'width',0.4705932,...
                    'height',0.6443976,...
                      'Snac',1.759411998,...
              'PowerTakeOff',469.791e+03,...
    'PowerMaximumContinuous',417.592e+03,...
                  'OmegaRPM',6120,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.631e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

