function eng = LTS101_750B_1(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter BK-117B (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'LTS101-750B-1'},...
                    'weight',133.812*g,...
                    'lenght',0.7889805,...
                     'width',0.4705932,...
                    'height',0.6441435,...
                      'Snac',1.759011038,...
              'PowerTakeOff',468.2996e+03,...
    'PowerMaximumContinuous',439.963e+03,...
                  'OmegaRPM',6140,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.800e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

