function eng = Makila1A1(atmosphere,numEngines)
%
% Author: Alejandro Redondo alex.redondo.moral@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS 332L1 / AS 532'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Makila 1A1'},...
                    'weight',234.9648*g,...
                    'lenght',2.10312,...
                     'width',0.49276,...
                    'height',0.68072,...
                      'Snac',4.9359385,...
              'PowerTakeOff',1357.174e3,...
    'PowerMaximumContinuous',883.6545e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',22850,...
                      'PSFC',8.17825e-08 ...
);

eng  = addEnginePerformance(eng,atmosphere);

