function eng = Makila1A(atmosphere,numEngines)
%
% Author: Alejandro Redondo alex.redondo.moral@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS 332'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Makila 1A'},...
                    'weight',243*g,...
                    'lenght',2.10312,...
                     'width',0.49276,...
                    'height',0.67818,...
                      'Snac',4.9252546656,...
              'PowerTakeOff',1240.0991e3,...
    'PowerMaximumContinuous',1129.7355e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',22850,...
                      'PSFC',9.766594e-08 ...
);

eng  = addEnginePerformance(eng,atmosphere);

