function eng = Makila1A2(atmosphere,numEngines)
%
% Author: Alejandro Redondo alex.redondo.moral@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter AS 332MK2 (2) / AS 532MK2'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Makila 1A2'},...
                    'weight',234.9648*g,...
                    'lenght',2.13106,...
                     'width',0.49276,...
                    'height',0.6731,...
                      'Snac',4.9359385,...
              'PowerTakeOff',1375.8165e3,...
    'PowerMaximumContinuous',1235.6249e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',22850,...
                      'PSFC',8.04307e-08 ...
);

eng  = addEnginePerformance(eng,atmosphere);

