function eng = Makila2A1(atmosphere,numEngines)
%
% Author: Alejandro Redondo alex.redondo.moral@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter EC 725 / EC 225 (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Makila 2A1'},...
                    'weight',278.9*g,...
                    'lenght',2.115,...
                     'width',0.668,...
                    'height',0.785,...
                      'Snac',6.14619,...
              'PowerTakeOff',1566.7157e3,...
    'PowerMaximumContinuous',1417.5757e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',22962,...
                      'PSFC',7.9248e-08 ...
);

eng  = addEnginePerformance(eng,atmosphere);

