function eng = Makila1K2(atmosphere,numEngines)
%
% Author: Alejandro Redondo alex.redondo.moral@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Denel Roivalk (2)'},...
              'manufacturer',{'Turbomeca'},...
                     'model',{'Makila 1K2'},...
                    'weight',247*g,...
                    'lenght',2.117,...
                     'width',0.498,...
                    'height',0.673,...
                      'Snac',4.958014,...
              'PowerTakeOff',1375.8165e3,...
    'PowerMaximumContinuous',1235.6249e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',22962,...
                      'PSFC',8.04308e-08 ...
);

eng  = addEnginePerformance(eng,atmosphere);

