function eng = MTR_390_2C(atmosphere,numEngines)
%
% Author: sergio Fernandez sergio.fernandezr@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Eurocopter Tiger (2)'},...
              'manufacturer',{'MTR'},...
                     'model',{'MTR_390_2C'},...
                    'weight',169.1928*g,...
                    'lenght',1.077384,...
                     'width',0.442134,...
                    'height',0.680988,...
                      'Snac',2.4200673,...
              'PowerTakeOff',971.647e3,...
    'PowerMaximumContinuous',885.1459e3,...
                  'OmegaRPM',8000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.67134e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);