function eng = PT6B_37A(atmosphere,numEngines)
%
% Author: Ivan Marq ivanmarq@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g = 9.81;
eng = struct( ...
               'helicopters',{'Augusta A119 Koala (1)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PT6B_37A'},...
                    'weight',174.636*g,...
                    'lenght',1.636404,...
                     'width',0.4495495,...
                    'height',0.894432,...
                      'Snac',4.5489642,...
              'PowerTakeOff',747.191e3,...
    'PowerMaximumContinuous',650.2504e3,...
                  'OmegaRPM',4505,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.00201e-07 ...
);


eng = addEnginePerformance(eng,atmosphere);