function eng = PT6B_36A(atmosphere,numEngines)
%
% Author: sergio Fernandez sergio.fernandezr@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'SIKORSKY S-76B (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PT6B_36A'},...
                    'weight',174.1824*g,...
                    'lenght',1.504272,...
                     'width',0.495495,...
                    'height',0.495495,...
                      'Snac',2.981437,...
              'PowerTakeOff',731.532e3,...
    'PowerMaximumContinuous',661.4359e3,...
                  'OmegaRPM',6469,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.81729e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);