function eng = PT6C_67A(atmosphere,numEngines)
%
% Author: Ivan Marq ivanmarq@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g = 9.81;
eng = struct( ...
               'helicopters',{'Bell Augusta BA609 (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PT6C_67A'},...
                    'weight',189.6048*g,...
                    'lenght',1.654191,...
                     'width',0.525987,...
                    'height',0.525987,...
                      'Snac',3.4803318,...
              'PowerTakeOff',1446.66e3,...
    'PowerMaximumContinuous',1249.048e3,...
                  'OmegaRPM',30000,...
             'powerExponent',0.85,...% FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8.60069e-8 ...
);


eng = addEnginePerformance(eng,atmosphere);