function eng = PT6C_67E(atmosphere,numEngines)
%
% Author: Ivan Marq ivanmarq@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g = 9.81;
eng = struct( ...
               'helicopters',{'EC175'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PT6C_67E'},...
                    'weight',210*g,...
                    'lenght',1.5246,...
                     'width',0.571725,...
                    'height',0.571725,...
                      'Snac',3.4866077,...
              'PowerTakeOff',1323.62e3,...
    'PowerMaximumContinuous',969.41e3,...
                  'OmegaRPM',21000,...
             'powerExponent',0.85,...% FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8.5331e-8 ...
);


eng = addEnginePerformance(eng,atmosphere);