function eng = PT6T_3(atmosphere,numEngines)
%
% Author: Ivan Marq ivanmarq@gmail.com
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g = 9.81;
eng = struct( ...
               'helicopters',{'Bell UH-1N,CUH-1,VH-1N,AH-1J,AH-1T, Augusta-Bell 212, SikorskyS-58T(1)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PT6T_3 Twin Pac'},...
                    'weight',293.932*g,...
                    'lenght',1.671978,...
                     'width',1.105335,...
                    'height',0.828366,...
                      'Snac',6.4662111,...
              'PowerTakeOff',1342.26e3,...
    'PowerMaximumContinuous',1193.12e3,...
                  'OmegaRPM',6600,...
             'powerExponent',0.85,...% FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.00538e-7 ...
);


eng  = addEnginePerformance(eng,atmosphere);