function eng = PW207K(atmosphere,numEngines)
%
% Author: Lucia Sanchez lucia.sanchez.iglesias@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Kazan Ansat (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PW207K'},...
                    'weight',108,4104*g,...
                    'lenght',0,912219,...
                     'width',0,500577,...
                    'height',0,566643,...
                      'Snac',1,94707672236,...
              'PowerTakeOff',537.28e3,...
    'PowerMaximumContinuous',466,0625e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.1245e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);