function eng = PW206C(atmosphere,numEngines)
%
% Author: Jose Garcia Garrido jose.garcia.garrido@alumnos.upm.es
% Date: 24/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Agusta A109 Power (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PW206C'},...
                    'weight',107.5032*g,...
                    'lenght',0.912219,...
                     'width',0.500577,...
                    'height',0.566643,...
                      'Snac',1.947076722,...
              'PowerTakeOff',477.248e+03,...
    'PowerMaximumContinuous',422.8119e+03,...
                  'OmegaRPM',6120,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.15829e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

