function eng = PW207D1(atmosphere,numEngines)
%
% Author: Lucia Sanchez lucia.sanchez.iglesias@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell 429 (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PW207D1'},...
                    'weight',107,5032*g,...
                    'lenght',0,792792,...
                     'width',0,500577,...
                    'height',0,569184,...
                      'Snac',1,696195925,...
              'PowerTakeOff',536,1583e3,...
    'PowerMaximumContinuous',473,5195e3,...
                  'OmegaRPM',6000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',9.1245e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

