function eng = PW206A(atmosphere,numEngines)
%
% Author: Maria Sanz mariass0@alumnos.upm.es
% Date: 13/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'MD Explorer'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PW206A'},...
                    'weight',107.5032*g,...
                    'lenght',0.912219,...
                     'width',0.500577,...
                    'height',0.566643,...
                      'Snac',1.947076722,...
              'PowerTakeOff',477.248e3,...
    'PowerMaximumContinuous',422.8119e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',6000,...
                       'PSFC',9.17519e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);