function eng = PW206B(atmosphere,numEngines)
%
% Author: Jose Garcia Garrido jose.garcia.garrido@alumnos.upm.es
% Date: 24/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'EC135P1 (2)'},...
              'manufacturer',{'Pratt & Whitney Canada'},...
                     'model',{'PW206B'},...
                    'weight',112.0392*g,...
                    'lenght',1.04181,...
                     'width',0.500577,...
                    'height',0.627627,...
                      'Snac',2.350748418,...
              'PowerTakeOff',463.0797e+03,...
    'PowerMaximumContinuous',419.0834e+03,...
                  'OmegaRPM',5898,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.25968e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

