function eng = RR250C20B(atmosphere,numEngines)
%
% Author: Lucia Sanchez lucia.sanchez.iglesias@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Agusta A1 09A (2), Bell 206B, JetRanger (1), Bell 206L, LongRanger (1), Eurocopter BO105 (2), Hiller FH1100 (1), MD Helicopters MD500D (1)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'250-C20B'},...
                    'weight',73,4832*g,...
                    'lenght',0,96558,...
                     'width',0,48279,...
                    'height',0,589512,...
                      'Snac',2,07078673032,...
              'PowerTakeOff',313,194e3,...
    'PowerMaximumContinuous',313,194e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',1.09831944444444e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);