function eng = RR250C30(atmosphere,numEngines)
%
% Author: Rocio Macarro rocio.martin.macarro@alumnos.upm.es
% Date: 18/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
%falta dato de omegaRPM en la hoja excel, el valor que aparece es el que
%tienen los motores de la misma serie
eng = struct( ...
               'helicopters',{'MD Helicopters MD530F (1)'},...
              'manufacturer',{'Rolls Royce'},...
                     'model',{'250-C30'},...
                    'weight',114.3072*g,...
                    'lenght',1.09728,...
                     'width',0.5588,...
                    'height',0.6477,...
                      'Snac',2.64773664,...
              'PowerTakeOff',484.705e3,...
    'PowerMaximumContinuous',415.3549e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.00031555555556e-7 ...
);


eng  = addEnginePerformance(eng,atmosphere);