function eng = RR250C28(atmosphere,numEngines)
%
% Author: Rocio Macarro rocio.martin.macarro@alumnos.upm.es
% Date: 18/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
%falta dato de omegaRPM en la hoja excel, el valor que aparece es el que
%tienen los motores de la misma serie
eng = struct( ...
               'helicopters',{'Eurocopter BO105LS (2)'},...
              'manufacturer',{'Rolls Royce'},...
                     'model',{'250-C28'},...
                    'weight',107.0496*g,...
                    'lenght',1.20142,...
                     'width',0.65532,...
                    'height',0.6477,...
                      'Snac',3.1309485768,...
              'PowerTakeOff',372.85e3,...
    'PowerMaximumContinuous',372.85e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.96936111111111e-8 ...
);
eng  = addEnginePerformance(eng,atmosphere);