function eng = RR250C28B(atmosphere,numEngines)
%
% Author: Rocio Macarro rocio.martin.macarro@alumnos.upm.es
% Date: 18/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
eng = struct( ...
               'helicopters',{'Bell 206L-1 LongRanger II (1)'},...
              'manufacturer',{'Rolls Royce'},...
                     'model',{'250-C28B'},...
                    'weight',107.9568*g,...
                    'lenght',1.20142,...
                     'width',0.65278,...
                    'height',0.6477,...
                      'Snac',3.1248453632,...
              'PowerTakeOff',372.85e3,...
    'PowerMaximumContinuous',372.85e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',9.96936111111111e-8 ...
);
eng  = addEnginePerformance(eng,atmosphere);