function eng = RR250C20F(atmosphere,numEngines)
%
% Author: Lucia Sanchez lucia.sanchez.iglesias@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'EurocopterAS355F (2)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'250-C20F'},...
                    'weight',73,4832*g,...
                    'lenght',0,9652,...
                     'width',0,4826,...
                    'height',0,58928,...
                      'Snac',2,069157152,...
              'PowerTakeOff',313,194e3,...
    'PowerMaximumContinuous',313,194e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',1.09831944444444e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);