function eng = RR250C20W(atmosphere,numEngines)
%
% Author: Rocio Macarro rocio.martin.macarro@alumnos.upm.es
% Date: 18/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g=9.81;
eng = struct( ...
               'helicopters',{'Enstrom 480B (1),Northrop Grumman Fire-Scout (1),Schweizer 330SP/333 (1)'},...
              'manufacturer',{'Rolls Royce'},...
                     'model',{'250-C20W'},...
                    'weight',73.4832*g,...
                    'lenght',0.98552,...
                     'width',0.47752,...
                    'height',0.57404,...
                      'Snac',2.0726668224,...
              'PowerTakeOff',313.194e3,...
    'PowerMaximumContinuous',313.194e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.09831944444444e-7 ...
);
eng  = addEnginePerformance(eng,atmosphere);