function eng = RR300(atmosphere,numEngines)
%
% Author: Lucia Sanchez lucia.sanchez.iglesias@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Robinson R66 (1)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'RR300'},...
                    'weight',79,8336*g,...
                    'lenght',1,097712,...
                     'width',0,55902,...
                    'height',0,63525,...
                      'Snac',2,62192902048,...
              'PowerTakeOff',223,71e3,...
    'PowerMaximumContinuous',178,968e3,...
                  'OmegaRPM',6016,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',1.13211388888889e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);