function eng = RR_250_B17F(atmosphere,numEngines)
%
% Author: Hector Fernandez hector.fdotu@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Groen Brothers Aviation Hawk4 (1), Q&N Silver Eagle (1), Soloy Cessna 206 Mark II (1)'},...
              'manufacturer',{'Rolls-Royce'},...
                     'model',{'250-B17F'},...
                    'weight',97.524*g,...
                    'lenght',1.143,...
                     'width',0.5588,...
                    'height',0.65278,...
                      'Snac',2.76967188,...
              'PowerTakeOff',335.565e3,...
    'PowerMaximumContinuous',335.565e3,...
                  'OmegaRPM',2013,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',10.358e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

