function eng = RTM322_01_8(atmosphere,numEngines)
%
% Author: Hector Fernandez hector.fdotu@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'AgustaWestland Merlin HC HM Mk1 (3)'},...
              'manufacturer',{'Rolls-Royce, Turbomeca'},...
                     'model',{'RTM322-01/8'},...
                    'weight',254.016*g,...
                    'lenght',1.17094,...
                     'width',0.65786,...
                    'height',0.60452,...
                      'Snac',2.956342474,...
              'PowerTakeOff',1566.7157e3,...
    'PowerMaximumContinuous',1373.5794e3,...
                  'OmegaRPM',20900,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.67134e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

