function eng = RTM322_02_8(atmosphere,numEngines)
%
% Author: Raquel Martin raquel.martin.sanroman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Augusta Westland Merlin HC Mk3(3)'},...
              'manufacturer',{'Rolls-Royce Turbomeca'},...
                     'model',{'RTM322-02/8'},...
                    'weight',252.2016*g,...
                    'lenght',1.17094,...
                     'width',0.65786,...
                    'height',0.60452,...
                      'Snac',2.956342474,...
              'PowerTakeOff',1687.52e3,...
    'PowerMaximumContinuous',1406.39e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',20900,...
                       'PSFC',7.65444e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);
