function eng = RTM322_01_9(atmosphere,numEngines)
%
% Author: Raquel Martin raquel.martin.sanroman@alumnos.upm.es
% Date: 17/03/2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'NHI NH90(2)'},...
              'manufacturer',{'Rolls-Royce Turbomeca'},...
                     'model',{'RTM322-01/9'},...
                    'weight',227.2536*g,...
                    'lenght',1.1176,...
                     'width',0.64008,...
                    'height',0.60198,...
                      'Snac',2.776252512,...
              'PowerTakeOff',1798.63e3,...
    'PowerMaximumContinuous',1664.402e3,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                  'OmegaRPM',20900,...
                       'PSFC',7.16442e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);