function eng = T5317A(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell 205A1'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'T5317A'},...
                    'weight',249.48*g,...
                    'lenght',1.209516,...
                     'width',0.622545,...
                    'height',0.622545,...
                      'Snac',3.0119126,...
              'PowerTakeOff',1118.55e+03,...
    'PowerMaximumContinuous',1006.695e+03,...
                  'OmegaRPM',6230,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.02e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);

