function eng = T53_L_13B(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'Bell UH-1 Agusta AB205'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'T53-L-13B'},...
                    'weight',249.0264*g,...
                    'lenght',1.209516,...
                     'width',0.622545,...
                    'height',0.622545,...
                      'Snac',3.0119126,...
              'PowerTakeOff',1043.98e+03,...
    'PowerMaximumContinuous',932.125e+03,...
                  'OmegaRPM',6600,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',1.01e-07 ...
);


eng  = addEnginePerformance(eng,atmosphere);

