function eng = T55_L_712F(atmosphere,numEngines)
%
% Author: Iker Camiruaga ikercamiruaga@gmail.com
% Date: 2012
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%

g   = 9.81;
eng = struct( ...
               'helicopters',{'HCMK2/2A (2)'},...
              'manufacturer',{'Honeywell Engines & Systems'},...
                     'model',{'T55-L-712F'},...
                    'weight',354.17088*g,...
                    'lenght',1.196811,...
                     'width',0.6161925,...
                    'height',0.6161925,...
                      'Snac',2.949863848,...
              'PowerTakeOff',3217.6955e+03,...
    'PowerMaximumContinuous',2348.955e+03,...
                  'OmegaRPM',15066,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                      'PSFC',8.871e-08 ...
);


eng  = addEnginePerformance(eng,atmosphere);

