function eng = T700_GE_401C(atmosphere,numEngines)
%
% Author: Hector Fernandez Dotu hector.fdotu@alumnos.upm.es
% Date: 2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'Sikorsky MH-60R, Sikorsky S-70B'},...
              'manufacturer',{'General Electric'},...
                     'model',{'T700-GE-401C'},...
                    'weight',208*g,...
                    'lenght',1.168,...
                     'width',0.6604,...
                    'height',0.584,...
                      'Snac',2.77,... %FALTA, LE HE PUESTO EL DEL RR3229A
              'PowerTakeOff',1.342e+06,...
    'PowerMaximumContinuous',1.239e+06,...
                  'OmegaRPM',21000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.65e-08 ... %Son (Kg/W)/s
);


eng  = addEnginePerformance(eng,atmosphere);

