function eng = T700_T6E(atmosphere,numEngines)
%
% Author: Hector Fernandez Dotu hector.fdotu@alumnos.upm.es
% Date: 2014
%
% TODO LIST 
% * fit powerExponent to actual data
% * modify addEnginePerformance to define PSFC dependency on altitute and
%  consequently define psfcExponent in case it makes sense to fit actual 
%  PSFC data with a power function of the altitude 
%
%


g   = 9.81;
eng = struct( ...
               'helicopters',{'NH90'},...
              'manufacturer',{'General Electric, Alfa Romeo Avio, FiatAvio'},...
                     'model',{'T700/T6E'},...
                    'weight',220*g,...
                    'lenght',1.2045,...
                     'width',0.6604,...
                    'height',0.6325,...
                      'Snac',2.77,... %FALTA, LE HE PUESTO EL DEL RR3229A
              'PowerTakeOff',1.652e+06,...
    'PowerMaximumContinuous',1.539e+06,...
                  'OmegaRPM',21000,...
             'powerExponent',0.85,... % FIXME: to be fitted with actual data
                'numEngines',numEngines,...
                       'PSFC',7.383e-08 ... %Son (Kg/W)/s
);


eng  = addEnginePerformance(eng,atmosphere);

