function CruiseRangePlan = MaxVelCruiseRangeBuilder(pos,DR,DPL,Omega)
% BestCruiseRangeSegmentBuilder builds the mission segment corresponding
% to a level cruise for given range increment, DR, and the minimum fuel 
% consumption for the maximum flight velocity.
%
% pos   [1x1 double]  is the segment position
% DR    [1x1 double]  is the range increment during the flight segment [m]
% DPL   [1x1 double]  is the payload variation during segment flight [N]
% Omega [1x1 double]  is the main rotor angular velocity [rad/s]
%
%
% The CruiseRangePlan is a structure with the following fields:
%
%     class: 'missionSegment'
%        id: 'CruiseRange'
%    solver: @getSegmentMaxVelCruiseRange
%       pos: [1x1 double]
%         V: [1x2 double]
%    gammaT: [1x2 double]
%        VH: [1x2 double]
%        VV: [1x2 double]
%     Omega: [1x2 double]
%         Z: [1x2 double]
%         H: [1x2 double]
%        DH: [1x1 double]
%         R: [1x2 double]
%        DR: [1x1 double]
%         T: [1x2 double]
%        DT: [1x1 double]
%        GW: [1x2 double]
%       DGW: [1x1 double]
%        Mf: [1x2 double]
%       DMf: [1x1 double]
%        PL: [1x2 double]
%       DPL: [1x1 double]
%         P: [1x2 double]
%


CruiseRangePlan = struct(...
    'class','missionSegment',...
       'id','CruiseRange',...
   'solver',@getSegmentMaxVelCruiseRange,...
      'pos',pos,...
        'V',[NaN NaN],...
   'gammaT',[0 0],...
       'VH',[NaN NaN],...
       'VV',[NaN NaN],...
    'Omega',[Omega Omega],...
        'Z',[NaN NaN],...
        'H',[NaN NaN],...
       'DH',0,...
        'R',[NaN NaN],...
       'DR',DR,...
        'T',[NaN NaN],...
       'DT',NaN,...
       'GW',[NaN NaN],...
      'DGW',NaN,...
       'Mf',[NaN NaN],...
      'DMf',NaN,...
       'PL',[NaN NaN],...
      'DPL',DPL,...
        'P',[NaN NaN]...
          );
    
end


