function f = Cuerva(lambda_i,CT,mux,muWx,muy,muWy,muzp)
% FIXME too much input arguments
A = 0.745;
B = 0.447;

f = CT + 2*A*lambda_i.* ...
    sqrt( (mux+muWx)^2 + ...
          (muy+muWy)^2 + ...
          (lambda_i+muzp)^2 + ...
          B^2*muzp^2);
