function f = Glauert(lambda_i,CT0,mux,muWx,muy,muWy,muzp)
% FIXME too much input arguments

f = CT0 + 2*lambda_i.* ...
    sqrt( (mux+muWx)^2 + ...
          (muy+muWy)^2 + ...
          (lambda_i+muzp)^2);
end