function validationtester(mode)

% validation tests
testList  = {...
             @padfieldFigure4_6b,...
             @padfieldFigure4_7,...
             @padfieldFigure4_8a,...
             @padfieldFigure4_8b,...
             @padfieldFigure4_9,...
             @padfieldTable4_1,...
             @validationTrimBo105,...
             @validationHeroesHelisimStaConDer, ...
             @gazelle_clcdNasa88351, ...
             @gazelle_fusNasa88351, ...
             @gazelle_htpNasa88351, ...
             @gazelle_stabNasa88351, ...
             @gazelle_trimNasa88351, ...
             @plotRigidGazelle, ...          
             @validationGazelleLocalTrim, ...
             @validationGazelleTrim, ...
             @validationGazelleTrim_lin_nl ...
            };

runTestList(testList,mode);

% for i=1:length(test),
%     io = test{i}();
%     runCheckTest(io,func2str(test{i}));
%     close all
% end