function transmission = eTransmission(Pmt,etaTmr,etaTtr)



% transmission definition
transmission = struct(...
            'class','transmission',...
            'id','eTransmission',...
            'etaTra',etaTtr,...
            'Pmt',Pmt, ...
            'etaTrp',etaTmr ...
);

