function he=bramwell
% Helicopter used in Bramwell to compute performance  chapter 4 pg 118

%ATM i do not have anyrhing better 
[cldata,cddata]=naca0012;
mr = struct(...
      'R',8,...
      'nb',4,...
      'cldata',[5.73 0],...
      'cddata',cddata,...
      'profile',@cl1cd2,...
      'Omega',208./8.,...
      'chord',0.05*pi*8.0/4.0, ...
      'kappa',1.17,...
      'K',3.0,...
      'cd0',0.013 ...
);


eng = struct(...
      'P_sl',900*1e3 ...% pg 129
);

% Given R/R_t = 5.21 (apache) is the most
% similar at first sight. 
% Considering equal tip speed 
% Omega_t*R_t=Omega*R then
% Omega_t =Omega*R/R_t
%
% Now, using the relationship given in page 129
% sigma_t*A_t/sigma*A=0.06 and assuming equal number
% of blades, then
% c_t = 0.06*c*R/R_t
tr = struct(...
      'R',8/5.21,...
      'nb',4,...
      'Omega',208.0/8.0*5.21,...
      'chord',0.06*0.05*8.0/(8.0/5.21), ...
      'kappa',1.17,...
      'K',3.0,...
      'cd0',0.013 ...
);

he  = struct(...
      'W',45000,...%MTOW [N] pg 118
      'f',2.3, ...% m^2 pg 118
      'x_tr',9.9,... % m^2 FIXME from leishman
      'mr',mr,...
      'tr',tr,...
      'eng',eng,...  % w
      'type','he'...
);
