function he = ehe(mainRotor,tailRotor,...
                  fuselage,...
                  powerPlant,transmission,...
                  atmosphere,weights,...
                  varargin)

if nargin == 7
   label   = 'ehe';
elseif nargin == 8
   label   = varargin{1};
else
   disp('ehe:wrong number of input arguments')
end


eta_ra               = tailRotor.eta;


% Fix transmission data
[etaMrp,etaMra,etaM] = getEtaM(transmission,eta_ra);
transmission.etaMrp  = etaMrp;
transmission.etaMra  = etaMra;
transmission.etaM    = etaM;


% Get available power taken into account transmission power limitation
availablePower = engine_transmission2availablePower(powerPlant,transmission);

he  = struct(...
      'class','ehe', ...
      'id',label,...
      'mainRotor',mainRotor,...
      'tailRotor',tailRotor,...
      'engine',powerPlant,... 
      'fuselage',fuselage, ...
      'transmission',transmission,...
      'weights',weights,...
      'availablePower',availablePower ...
);


% atmosphere seems not very clear that it is convenient to be input FIXME
he      = addCharacteristic2he(he,atmosphere);

