function he=superPuma(atmosphere)
% super puma SA330 from Padfield pages 264-266
% FIXME the name of this ehe is confussing. In fact, this ehe is the energy
% helciopter that corresponds to the helicopter data of the exercise of the
% energy method of the topic HA1. I seem to remember that Alvaro told me
% that this was the superPuma however it is quite different from the data
% used at Padfield. I propose to rename the ehe to exHa1 or something
% like that in order to avoid confussion
% Helicopter definition

label = 'superPuma';

% main rotor definition
mainRotor = struct(...
            'class','rotor',...
            'id',label,...
            'eta',0.06,...
            'R',16.19/2,...% 
            'b',4,...% 
            'cldata',[5.73 0],...% 
            'cddata',[0.263 0.0 0.01],...% my own
            'profile',@cl1cd2,...
            'Omega',265*2*pi/60,... % 
            'c',0.6, ... % 
            'kappa',1.15,... % my own 
            'K',4.5,...% my own
            'cd0', 0.01...
);


% engine definition
% This data lacks reference. Nobody knows where these data come from?
numEng  = 2;
Pmc     = 1236e3;
Pde     = 1373e3;
n       = 0.85;
PSFC    = 370e-6/3600;

% g   = 9.81;
engine = struct( ...
               'helicopters',{'AS330'},...
              'manufacturer',{'who?'},...
                     'model',{'which?'},...
                    'weight',NaN,...
                    'lenght',NaN,...
                     'width',NaN,...
                    'height',NaN,...
                      'Snac',NaN,...
              'PowerTakeOff',Pde,...
    'PowerMaximumContinuous',Pmc,...
             'powerExponent',n,... % FIXME: to be fitted with actual data
                'numEngines',numEng,...
                  'OmegaRPM',NaN,...
                       'PSFC',PSFC ...
);


engine  = addEnginePerformance(engine,atmosphere);
% FIXME to avoid right now the burden of fixing addEnginePerformance to 
% add properly the maximum urgency power we override the values by rewriten
% the engine structure
Pmu         = numEng*1400e3;
engine.Pmu     = Pmu;
engine.fPmu    = @(h) engPower(h,Pmu,n,atmosphere.density);


% tail rotor definition
tailRotor = struct(...
            'class','rotor',...
            'id',label,...
            'eta',0.06,...
            'R',1.106,...% Padfield pg 260
            'b',4,...% Padfield pg 261
            'cldata',[5.73 0],...% my own
            'cddata',[0.0 0.0 0.01],...% my own
            'Omega',195,...% my own (equal tip speed)
            'c',0.208*pi*1.106/4, ...% Padfield pg 260
            'kappa',1.1,...
            'K',3,...
            'cd0', 0.01...
);


% fuselage definition
fuselage   = struct(...
            'class','fuselage',...
            'id',label,...
             'f',2.2 ...
);

% transmission definition
transmission = struct(...
            'class','transmission',...
            'id',label,...
            'etaTra',0.07,...
            'etaTrp',0.12 ...
);


Pmt     = 2410*1e3;
fPmt    = @(h) Pmt*ones(size(h));

% FIXME discuss about this point
[etaMrp,etaMra,etaM] = getEtaM(transmission,tailRotor.eta);
transmission.etaMrp  = etaMrp;
transmission.etaMra  = etaMra;
transmission.etaM    = etaM;
transmission.fPmt    = fPmt;
transmission.Pmt     = Pmt;

% Weights
% From wikipedia http://en.wikipedia.org/wiki/Eurocopter_AS332_Super_Puma
% MTOW = 9150; OEW=4660 useful load = 4490 kg
% From BlueBook
% MTOW = 8350; OEW=4200 useful load = 4150 kg fuel tank 1250 kg
weights.MTOW = 8350*atmosphere.g;
weights.OEW  = 4200*atmosphere.g;
weights.MPL  = 2900*atmosphere.g; % FIXME this is Oscar's invention
weights.MFW  = 1250*atmosphere.g;

% Get available power taken into account transmission power limitation
availablePower = engine_transmission2availablePower(engine,transmission);

% helicopter definition
he  = struct(...
      'class','ehe', ...
      'id',label,...
      'mainRotor',mainRotor,...
      'tailRotor',tailRotor,...
      'engine',engine,... 
      'fuselage',fuselage, ...
      'transmission',transmission,...
      'weights',weights,...
      'availablePower',availablePower ...
);

% Old values before 2014 overhaul
% % % % % % %       'Mf',1600,...
% % % % % % %       'W',7500*atmosphere.g,...% N
% % % % % % %       'x_tr',8 ... % inventado


% atmosphere seems not very clear that it is convenient to be input FIXME
he      = addCharacteristic2he(he,atmosphere);
